country_codes = {'Afghanistan':'AFG', 'Albanien':'ALB',
                'Algerien':'DZA','Angola':'AGO','Argentinien':'ARG',
                'Armenien':'ARM', 'Aserbaidschan':'AZE',
                'Bangladesch':'BGD', 'Benin':'BEN',
                'Bhutan':'BTN', 'Bolivien':'BOL',
                'Bosnien-Herzegowina':'BIH','Brasilien':'BRA',
                'Burkina Faso':'BFA', 'Burundi':'BDI',
                'Chile':'CHL', 'China':'CHN', 'Costa Rica':'CRI',
                'Djibouti':'DJI', 'El Salvador':'SLV',
                'Elfenbeinküste':'CIV', 'Equateur':'ECU',
                'Eritrea':'ERI', 'Gaza und Westbank':'PSE',
                'Georgien':'GEO', 'Ghana':'GHA',
                'Guatemala':'GTM', 'Guinea':'GIN',
                'Guinea-Bissau':'GNB', 'Haiti':'HTI',
                'Honduras':'HND', 'Indien':'IND',
                'Indonesien':'IDN', 'Irak':'IRQ', 'Iran':'IRN',
                'Jemen':'YEM', 'Jordanien':'JOR',
                'Kambodscha':'KHM', 'Kamerun':'CMR',
                'Kapverden':'CPV', 'Kasachstan':'KAZ',
                'Kenia':'KEN', 'Kirgisistan':'KGZ',
                'Kolumbien':'COL', 'Kongo (D. R.)':'COD',
                'Kosovo':'XKX', 'Kuba':'CUB', 'Laos':'LAO',
                'Lesotho':'LSO', 'Libanon':'LBN',
                'Liberia':'LBR', 'Libyen':'LBY',
                'Madagaskar':'MDG', 'Malawi':'MWI', 'Mali':'MLI',
                'Marokko':'MAR', 'Mauretanien':'MRT',
                'Mazedonien':'MKD', 'Mexiko':'MEX',
                'Moldawien':'MDA', 'Mongolei':'MNG',
                'Montenegro':'MNE', 'Mosambik':'MOZ',
                'Myanmar':'MMR', 'Namibia':'NAM', 'Nepal':'NPL',
                'Nicaragua':'NIC', 'Niger':'NER',
                'Nigeria':'NGA', 'Nordkorea':'PRK',
                'Pakistan':'PAK', 'Paraguay':'PRY', 'Peru':'PER',
                'Philippinen':'PHL', 'Republik Kongo':'COG',
                'Ruanda':'RWA', 'Sambia':'ZMB', 'Senegal':'SEN',
                'Serbien':'SRB', 'Sierra Leone':'SLE',
                'Simbabwe':'ZWE', 'Somalia':'SOM', 'Sri Lanka':'LKA',
                 'Sudan':'SDN', 'Syrien':'SYR',
                'Südafrika':'ZAF', 'Südsudan':'SSD',
                'Tadschikistan':'TJK', 'Tansania':'TZA',
                'Thailand':'THA', 'Togo':'TGO', 'Tschad':'TCD',
                'Tunesien':'TUN', 'Turkmenistan':'TKM',
                'Türkei':'TUR', 'Uganda':'UGA', 'Ukraine':'UKR',
                'Uruguay':'URY', 'Usbekistan':'UZB',
                'Vietnam':'VNM', 'Weissrussland':'BLR',
                'Zentralafrikanische Republik':'CAF',
                'Ägypten':'EGY', 'Äquatorialguinea':'GNQ',
                'Äthiopien':'ETH'}
